import {
    mobile,
    backend,
    web,
    javascript,
    typescript,
    html,
    css,
    reactjs,
    redux,
    tailwind,
    nodejs,
    mongodb,
    git,
    insta,
    zillow,
    dalle,
    vacation,
    threejs,
  } from "../assets";
  
  export const navLinks = [
    {
      id: "about",
      title: "About",
    },
    {
      id: "work",
      title: "Work",
    },
    {
      id: "contact",
      title: "Contact",
    },
  ];
  
  const services = [
    {
      title: "Web Developer",
      icon: web,
    },
    {
      title: "React Developer",
      icon: mobile,
    },
    {
      title: "Backend Developer",
      icon: backend,
    },
  ];
  
  const technologies = [
    {
      name: "HTML 5",
      icon: html,
    },
    {
      name: "CSS 3",
      icon: css,
    },
    {
      name: "JavaScript",
      icon: javascript,
    },
    {
      name: "TypeScript",
      icon: typescript,
    },
    {
      name: "React JS",
      icon: reactjs,
    },
    {
      name: "Redux Toolkit",
      icon: redux,
    },
    {
      name: "Tailwind CSS",
      icon: tailwind,
    },
    {
      name: "Node JS",
      icon: nodejs,
    },
    {
      name: "MongoDB",
      icon: mongodb,
    },
    {
      name: "Three JS",
      icon: threejs,
    },
    {
      name: "git",
      icon: git,
    },
  ];
  
  const experiences = [
    {
      title: "InstaPic",
      company_name: "Instagram Clone",
      icon: insta,
      iconBg: "#383E56",
      points: [
        "Authentication",
        "Image Upload",
        "Commenting",
        "Commenting History",
        "Like Functionality",
      ],
      source_code_link: "https://github.com/coderCkishan/Instapic",
    },
    {
      title: "Millow",
      company_name: "Zillow Clone",
      icon: zillow,
      iconBg: "#E6DEDD",
      points: [
        "Seller can list their property using metamask",
        "Buyer can buy listed property",
        "Lender can approves and give funds using metamask",
      ],
      source_code_link: "https://github.com/coderCkishan/millow",
    },
  ];
  
  const projects = [
    {
      name: "DallE Community Showcase",
      description:
        "Web-based platform that allows users to Search, Upload, and Download their images which have generated by OpenAI API DALLE",
      tags: [
        {
          name: "React",
          color: "blue-text-gradient",
        },
        {
          name: "MongoDB",
          color: "green-text-gradient",
        },
        {
          name: "NodeJS",
          color: "pink-text-gradient",
        },
      ],
      image: dalle,
      source_code_link: "https://github.com/coderCkishan/DallE-Community-showcase",
    },
    {
      name: "Vacation Vibes",
      description:
        "Web application that enables users to Search, Edit, Delete on thier post. Other functionality like commenting, tag-based search, pagination are also there.",
      tags: [
        {
          name: "React",
          color: "blue-text-gradient",
        },
        {
          name: "MongoDB",
          color: "green-text-gradient",
        },
        {
          name: "MaterialUI",
          color: "pink-text-gradient",
        },
      ],
      image: vacation,
      source_code_link: "https://github.com/coderCkishan/Vacation-Vibes",
    },
  ];
  
  export { services, technologies, experiences, projects };